### ISSUE TITLE
文档中资源链接版本错误

### ISSUE THREAD

**Issue by niubods** [think2011/lodash-zh#2]
整体文档版本标称为4.5.0，但是在“入门指南”和“单页面方式浏览”中，提供lodash的几个版本的下载链接没有更新，仍是3.10.1。

由于大版本升级导致API有几处破坏性变动，在本站下载的lodash，对照API文档执行出错就太尴尬了。

**Comment by think2011** [comment]
非常感谢，现版本也落后不少了，找个时间更新一下。
